yarnPath: .yarn/releases/yarn-4.8.1.cjs
nodeLinker: node-modules

packageExtensions:
  "eslint-plugin-storybook@0.12.0":
    peerDependencies:
      typescript: "*"

  "@storybook/react-vite@8.6.14":
    peerDependencies:
      typescript: "*"

  "@storybook/experimental-addon-test@8.6.14":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@storybook/addon-docs@8.6.14":
    peerDependencies:
      "@types/react": "*"

  "@storybook/addon-essentials@8.6.14":
    peerDependencies:
      "@types/react": "*"

  "@chromatic-com/storybook@3.2.6":
    peerDependencies:
      react: "*"

  "@storybook/core@8.6.14":
    peerDependencies:
      storybook: "*"
